import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

/**
 * Layer import boundaries. These are what keep the atomic hierarchy and the
 * mock data boundary real rather than aspirational: without them, a single
 * shortcut import turns "swap the mock for a real backend" into a refactor.
 *
 * All patterns for a file group live in one rule on purpose — flat config
 * replaces a rule's options rather than merging them, so a second
 * `no-restricted-imports` block would silently disable the first.
 */
const mockBoundary = {
  group: ['@/data/mock', '@/data/mock/**', '**/data/mock/**'],
  message:
    'Import from "@/data/repository" instead. Fixtures must stay behind the data-access boundary.',
};

const layerBoundaries = (layer, forbidden) =>
  forbidden.map((target) => ({
    group: [`@/components/${target}`, `@/components/${target}/**`, `**/${target}/**`],
    message: `atomic design: "${layer}" may not import from "${target}".`,
  }));

const restrict = (patterns) => ({
  'no-restricted-imports': ['error', { patterns }],
});

const layerRule = (layer, forbidden) => ({
  files: [`src/components/${layer}/**/*.{ts,tsx}`],
  rules: restrict([mockBoundary, ...layerBoundaries(layer, forbidden)]),
});

const eslintConfig = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),

  {
    ignores: ['.next/**', 'node_modules/**', 'design/**', 'Assets/**', 'next-env.d.ts'],
  },

  {
    rules: {
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },

  {
    // Fixtures are an implementation detail of the repository, not of the UI.
    files: ['src/**/*.{ts,tsx}'],
    ignores: ['src/data/**'],
    rules: restrict([mockBoundary]),
  },

  layerRule('atoms', ['molecules', 'organisms', 'templates']),
  layerRule('molecules', ['organisms', 'templates']),
  layerRule('organisms', ['templates']),

  {
    // Generated by the shadcn CLI and regenerable — not ours to police.
    files: ['src/components/ui/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
    },
  },
];

export default eslintConfig;
